.LIB ff_lib
.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ff/NMOS_VTG.inc'
.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ff/PMOS_VTG.inc'

.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ff/NMOS_VTL.inc'
.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ff/PMOS_VTL.inc'

.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ff/NMOS_VTH.inc'
.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ff/PMOS_VTH.inc'

.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ff/NMOS_THKOX.inc'
.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ff/PMOS_THKOX.inc'
.ENDL ff_lib

.LIB tt_lib
.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_nom/NMOS_VTG.inc'
.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_nom/PMOS_VTG.inc'

.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_nom/NMOS_VTL.inc'
.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_nom/PMOS_VTL.inc'

.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_nom/NMOS_VTH.inc'
.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_nom/PMOS_VTH.inc'

.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_nom/NMOS_THKOX.inc'
.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_nom/PMOS_THKOX.inc'
.ENDL tt_lib

.LIB ss_lib
.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ss/NMOS_VTG.inc'
.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ss/PMOS_VTG.inc'

.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ss/NMOS_VTL.inc'
.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ss/PMOS_VTL.inc'

.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ss/NMOS_VTH.inc'
.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ss/PMOS_VTH.inc'

.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ss/NMOS_THKOX.inc'
.inc '/gscratch/ece/pdks/FreePDK45_Nangate/FreePDK45/ncsu_basekit/models/hspice/tran_models/models_ss/PMOS_THKOX.inc'
.ENDL ss_lib
