#!/usr/bin/python
import sys
import os
import re
from optparse import OptionParser
import getpass

#Example
# xnetlist -l clocking -c charge_pump -v schematic -d /home/sathe/proj/clocking/cadence -n /home/sathe/proj/clocking/spice

parser = OptionParser()
parser.add_option("-l", "--library", dest="library", help="CDS library name")
parser.add_option("-c", "--cell", dest="cell", help="CDS cell name")
parser.add_option("-v", "--view", dest="view", default="schematic", help="CDS view name [default: %default]")
parser.add_option("-d", "--design", dest="design", default="~/cadence/tsmc65", help="CDS design directory location [default: %default]")
parser.add_option("-n", "--netlist", dest="netlist", default=".", help="Output netlist location [default: %default]")
parser.add_option("-t", "--topsub", dest="topsub", action="store_true", default=False, help="Create top level as a subcircuit [default: %default]")
(options,args) = parser.parse_args()

cwd=os.getcwd()
os.chdir(options.design)
#Generate ocean shell
filename = "xnetlist_" + options.library + "_" + options.cell + ".ocn"
ocnfile = "/tmp/xnetlist_" + getpass.getuser() + ".ocn"
fh=open(ocnfile,"w")
# fh=open("/tmp/xnetlist.ocn","w")
fh.write(";Autogenerated code for netlisting]\n")
fh.write(";LibName:%s CellName:%s ViewName:%s\n" % (options.library, options.cell, options.view))
fh.write("ocnxlProjectDir(\"%s\")\n" % options.netlist)
fh.write("simulator(\"hspiceD\")\n")
fh.write("design(\"%s\" \"%s\" \"%s\")\n" % (options.library, options.cell, options.view))
if(options.topsub):
    fh.write("envOption(\'setTopLevelAsSubckt t)\n")
fh.write("createNetlist(?recreateAll t  ?display nil)\n")
fh.close()

#Execute the ocean shell

os.system("ocean -64 < {0}".format(ocnfile))
os.chdir(cwd)
# move file out of directory and delete directory
# os.system("mv %s/%s/hspiceD/schematic/netlist/input.ckt %s/%s.ckt" % (options.netlist, options.cell, options.netlist, options.cell))
# os.system("rm -rf %s/%s" % (options.netlist, options.cell))

